version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: fintrackdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  pgdata:
